12. Exception in constructor
What will be printed to stdout in the following piece of code?

#include <iostream>

struct A
{
    A()
    {
        throw 2;
    }
};

struct B
{
    B()
        try 
        {
            A a;
        }
        catch (int i) 
        {
            std::cout << i;
        }
};

int main() 
{
    B b;
    std::cout << 3;
    return 0;
}
 

 

 

 

Pick ONE option
￼23
￼nothing
￼2
￼the code will not compile
